/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UnitInfo = IDL.Record({
  'portNumber' : IDL.Text,
  'unitName' : IDL.Text,
});
export const ControlsType = IDL.Variant({
  'stock' : IDL.Null,
  'reliable' : IDL.Null,
  'wattmaster' : IDL.Null,
  'niagara' : IDL.Null,
});
export const CradlepointModel = IDL.Variant({
  'ibr600C150M' : IDL.Null,
  'ibr700C4D' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Device = IDL.Record({
  'id' : IDL.Nat,
  'deviceAddress' : IDL.Text,
  'needsAttention' : IDL.Bool,
  'customer' : IDL.Text,
  'jobName' : IDL.Text,
  'isActive' : IDL.Bool,
  'lastModified' : IDL.Int,
  'notes' : IDL.Text,
  'controlsType' : ControlsType,
  'dateExpiration' : IDL.Int,
  'dateDeployed' : IDL.Int,
  'unlicensed' : IDL.Bool,
  'offline' : IDL.Bool,
  'unitAmount' : IDL.Nat,
  'cradlepointModel' : IDL.Opt(CradlepointModel),
  'ipAddress' : IDL.Text,
  'unitInfo' : IDL.Vec(UnitInfo),
  'simCardNumber' : IDL.Opt(IDL.Text),
  'anyDeskAddress' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const DeviceCounts = IDL.Record({
  'active' : IDL.Nat,
  'expired' : IDL.Nat,
  'stock' : IDL.Nat,
  'reliable' : IDL.Nat,
  'wattmaster' : IDL.Nat,
  'niagara' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addDevice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Vec(UnitInfo),
        ControlsType,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(CradlepointModel),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getActiveDevices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'getAllDevices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], ['query']),
  'getDevice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(Device)],
      ['query'],
    ),
  'getDeviceCounts' : IDL.Func([IDL.Text, IDL.Text], [DeviceCounts], ['query']),
  'getDevicesByType' : IDL.Func(
      [IDL.Text, IDL.Text, ControlsType],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'getExpiredDevices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'getInactiveDevices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleDeviceStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateDevice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Vec(UnitInfo),
        ControlsType,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(CradlepointModel),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'validateIpAddress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UnitInfo = IDL.Record({
    'portNumber' : IDL.Text,
    'unitName' : IDL.Text,
  });
  const ControlsType = IDL.Variant({
    'stock' : IDL.Null,
    'reliable' : IDL.Null,
    'wattmaster' : IDL.Null,
    'niagara' : IDL.Null,
  });
  const CradlepointModel = IDL.Variant({
    'ibr600C150M' : IDL.Null,
    'ibr700C4D' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Device = IDL.Record({
    'id' : IDL.Nat,
    'deviceAddress' : IDL.Text,
    'needsAttention' : IDL.Bool,
    'customer' : IDL.Text,
    'jobName' : IDL.Text,
    'isActive' : IDL.Bool,
    'lastModified' : IDL.Int,
    'notes' : IDL.Text,
    'controlsType' : ControlsType,
    'dateExpiration' : IDL.Int,
    'dateDeployed' : IDL.Int,
    'unlicensed' : IDL.Bool,
    'offline' : IDL.Bool,
    'unitAmount' : IDL.Nat,
    'cradlepointModel' : IDL.Opt(CradlepointModel),
    'ipAddress' : IDL.Text,
    'unitInfo' : IDL.Vec(UnitInfo),
    'simCardNumber' : IDL.Opt(IDL.Text),
    'anyDeskAddress' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const DeviceCounts = IDL.Record({
    'active' : IDL.Nat,
    'expired' : IDL.Nat,
    'stock' : IDL.Nat,
    'reliable' : IDL.Nat,
    'wattmaster' : IDL.Nat,
    'niagara' : IDL.Nat,
  });
  
  return IDL.Service({
    'addDevice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Vec(UnitInfo),
          ControlsType,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(CradlepointModel),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getActiveDevices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'getAllDevices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], ['query']),
    'getDevice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(Device)],
        ['query'],
      ),
    'getDeviceCounts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DeviceCounts],
        ['query'],
      ),
    'getDevicesByType' : IDL.Func(
        [IDL.Text, IDL.Text, ControlsType],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'getExpiredDevices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'getInactiveDevices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleDeviceStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateDevice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Vec(UnitInfo),
          ControlsType,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(CradlepointModel),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'validateIpAddress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };