/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ControlsType = { 'stock' : null } |
  { 'reliable' : null } |
  { 'wattmaster' : null } |
  { 'niagara' : null };
export type CradlepointModel = { 'ibr600C150M' : null } |
  { 'ibr700C4D' : null };
export interface Device {
  'id' : bigint,
  'deviceAddress' : string,
  'needsAttention' : boolean,
  'customer' : string,
  'jobName' : string,
  'isActive' : boolean,
  'lastModified' : bigint,
  'notes' : string,
  'controlsType' : ControlsType,
  'dateExpiration' : bigint,
  'dateDeployed' : bigint,
  'unlicensed' : boolean,
  'offline' : boolean,
  'unitAmount' : bigint,
  'cradlepointModel' : [] | [CradlepointModel],
  'ipAddress' : string,
  'unitInfo' : Array<UnitInfo>,
  'simCardNumber' : [] | [string],
  'anyDeskAddress' : [] | [string],
}
export interface DeviceCounts {
  'active' : bigint,
  'expired' : bigint,
  'stock' : bigint,
  'reliable' : bigint,
  'wattmaster' : bigint,
  'niagara' : bigint,
}
export interface UnitInfo { 'portNumber' : string, 'unitName' : string }
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addDevice' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      string,
      string,
      string,
      boolean,
      bigint,
      Array<UnitInfo>,
      ControlsType,
      boolean,
      boolean,
      boolean,
      [] | [string],
      [] | [CradlepointModel],
      [] | [string],
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticate' : ActorMethod<[string, string], boolean>,
  'deleteDevice' : ActorMethod<[string, string, bigint], undefined>,
  'getActiveDevices' : ActorMethod<[string, string], Array<Device>>,
  'getAllDevices' : ActorMethod<[string, string], Array<Device>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[string, string], bigint>,
  'getDevice' : ActorMethod<[string, string, bigint], [] | [Device]>,
  'getDeviceCounts' : ActorMethod<[string, string], DeviceCounts>,
  'getDevicesByType' : ActorMethod<
    [string, string, ControlsType],
    Array<Device>
  >,
  'getExpiredDevices' : ActorMethod<[string, string], Array<Device>>,
  'getInactiveDevices' : ActorMethod<[string, string], Array<Device>>,
  'getNetCloudKeyStatus' : ActorMethod<[string, string], { 'hasKeys' : boolean, 'lastSyncTime' : bigint, 'lastSyncStatus' : string }>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pollNetCloud' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNetCloudKeys' : ActorMethod<[string, string, string, string, string, string], undefined>,
  'toggleDeviceStatus' : ActorMethod<[string, string, bigint], undefined>,
  'transform' : ActorMethod<[any], any>,
  'updateDevice' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      [] | [bigint],
      string,
      string,
      string,
      boolean,
      bigint,
      Array<UnitInfo>,
      ControlsType,
      boolean,
      boolean,
      boolean,
      [] | [string],
      [] | [CradlepointModel],
      [] | [string],
    ],
    undefined
  >,
  'validateIpAddress' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
