/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UnitInfo {
    portNumber: string;
    unitName: string;
}
export interface DeviceCounts {
    active: bigint;
    expired: bigint;
    stock: bigint;
    reliable: bigint;
    wattmaster: bigint;
    niagara: bigint;
}
export interface UserProfile {
    username: string;
    name: string;
}
export interface Device {
    id: bigint;
    deviceAddress: string;
    needsAttention: boolean;
    customer: string;
    jobName: string;
    isActive: boolean;
    lastModified: bigint;
    notes: string;
    controlsType: ControlsType;
    dateExpiration: bigint;
    dateDeployed: bigint;
    unlicensed: boolean;
    offline: boolean;
    unitAmount: bigint;
    cradlepointModel?: CradlepointModel;
    ipAddress: string;
    unitInfo: Array<UnitInfo>;
    simCardNumber?: string;
    anyDeskAddress?: string;
}
export enum ControlsType {
    stock = "stock",
    reliable = "reliable",
    wattmaster = "wattmaster",
    niagara = "niagara"
}
export enum CradlepointModel {
    ibr600C150M = "ibr600C150M",
    ibr700C4D = "ibr700C4D"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addDevice(username: string, password: string, jobName: string, ipAddress: string, dateDeployed: bigint, dateExpiration: bigint | null, notes: string, deviceAddress: string, customer: string, isActive: boolean, unitAmount: bigint, unitInfo: Array<UnitInfo>, controlsType: ControlsType, offline: boolean, unlicensed: boolean, needsAttention: boolean, anyDeskAddress: string | null, cradlepointModel: CradlepointModel | null, simCardNumber: string | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticate(username: string, password: string): Promise<boolean>;
    deleteDevice(username: string, password: string, id: bigint): Promise<void>;
    getActiveDevices(username: string, password: string): Promise<Array<Device>>;
    getAllDevices(username: string, password: string): Promise<Array<Device>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTime(username: string, password: string): Promise<bigint>;
    getDevice(username: string, password: string, id: bigint): Promise<Device | null>;
    getDeviceCounts(username: string, password: string): Promise<DeviceCounts>;
    getDevicesByType(username: string, password: string, deviceType: ControlsType): Promise<Array<Device>>;
    getExpiredDevices(username: string, password: string): Promise<Array<Device>>;
    getInactiveDevices(username: string, password: string): Promise<Array<Device>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleDeviceStatus(username: string, password: string, id: bigint): Promise<void>;
    updateDevice(username: string, password: string, id: bigint, jobName: string, ipAddress: string, dateDeployed: bigint, dateExpiration: bigint | null, notes: string, deviceAddress: string, customer: string, isActive: boolean, unitAmount: bigint, unitInfo: Array<UnitInfo>, controlsType: ControlsType, offline: boolean, unlicensed: boolean, needsAttention: boolean, anyDeskAddress: string | null, cradlepointModel: CradlepointModel | null, simCardNumber: string | null): Promise<void>;
    validateIpAddress(username: string, password: string, ipAddress: string, jobName: string, excludeDeviceId: bigint | null): Promise<boolean>;
}
import type { ControlsType as _ControlsType, CradlepointModel as _CradlepointModel, Device as _Device, UnitInfo as _UnitInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDevice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint | null, arg6: string, arg7: string, arg8: string, arg9: boolean, arg10: bigint, arg11: Array<UnitInfo>, arg12: ControlsType, arg13: boolean, arg14: boolean, arg15: boolean, arg16: string | null, arg17: CradlepointModel | null, arg18: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDevice(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg12), arg13, arg14, arg15, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg16), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg17), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg18));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDevice(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg12), arg13, arg14, arg15, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg16), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg17), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg18));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticate(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0, arg1);
            return result;
        }
    }
    async deleteDevice(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDevice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDevice(arg0, arg1, arg2);
            return result;
        }
    }
    async getActiveDevices(arg0: string, arg1: string): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDevices(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDevices(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDevices(arg0: string, arg1: string): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTime(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime(arg0, arg1);
            return result;
        }
    }
    async getDevice(arg0: string, arg1: string, arg2: bigint): Promise<Device | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevice(arg0, arg1, arg2);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevice(arg0, arg1, arg2);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeviceCounts(arg0: string, arg1: string): Promise<DeviceCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceCounts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceCounts(arg0, arg1);
            return result;
        }
    }
    async getDevicesByType(arg0: string, arg1: string, arg2: ControlsType): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevicesByType(arg0, arg1, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevicesByType(arg0, arg1, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpiredDevices(arg0: string, arg1: string): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiredDevices(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiredDevices(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInactiveDevices(arg0: string, arg1: string): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveDevices(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveDevices(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleDeviceStatus(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDeviceStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDeviceStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDevice(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: bigint, arg6: bigint | null, arg7: string, arg8: string, arg9: string, arg10: boolean, arg11: bigint, arg12: Array<UnitInfo>, arg13: ControlsType, arg14: boolean, arg15: boolean, arg16: boolean, arg17: string | null, arg18: CradlepointModel | null, arg19: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDevice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11, arg12, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg13), arg14, arg15, arg16, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg17), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg18), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg19));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDevice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11, arg12, to_candid_ControlsType_n2(this._uploadFile, this._downloadFile, arg13), arg14, arg15, arg16, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg17), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg18), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg19));
            return result;
        }
    }
    async validateIpAddress(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateIpAddress(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateIpAddress(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_ControlsType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ControlsType): ControlsType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CradlepointModel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CradlepointModel): CradlepointModel {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CradlepointModel]): CradlepointModel | null {
    return value.length === 0 ? null : from_candid_CradlepointModel_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Device]): Device | null {
    return value.length === 0 ? null : from_candid_Device_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deviceAddress: string;
    needsAttention: boolean;
    customer: string;
    jobName: string;
    isActive: boolean;
    lastModified: bigint;
    notes: string;
    controlsType: _ControlsType;
    dateExpiration: bigint;
    dateDeployed: bigint;
    unlicensed: boolean;
    offline: boolean;
    unitAmount: bigint;
    cradlepointModel: [] | [_CradlepointModel];
    ipAddress: string;
    unitInfo: Array<_UnitInfo>;
    simCardNumber: [] | [string];
    anyDeskAddress: [] | [string];
}): {
    id: bigint;
    deviceAddress: string;
    needsAttention: boolean;
    customer: string;
    jobName: string;
    isActive: boolean;
    lastModified: bigint;
    notes: string;
    controlsType: ControlsType;
    dateExpiration: bigint;
    dateDeployed: bigint;
    unlicensed: boolean;
    offline: boolean;
    unitAmount: bigint;
    cradlepointModel?: CradlepointModel;
    ipAddress: string;
    unitInfo: Array<UnitInfo>;
    simCardNumber?: string;
    anyDeskAddress?: string;
} {
    return {
        id: value.id,
        deviceAddress: value.deviceAddress,
        needsAttention: value.needsAttention,
        customer: value.customer,
        jobName: value.jobName,
        isActive: value.isActive,
        lastModified: value.lastModified,
        notes: value.notes,
        controlsType: from_candid_ControlsType_n13(_uploadFile, _downloadFile, value.controlsType),
        dateExpiration: value.dateExpiration,
        dateDeployed: value.dateDeployed,
        unlicensed: value.unlicensed,
        offline: value.offline,
        unitAmount: value.unitAmount,
        cradlepointModel: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.cradlepointModel)),
        ipAddress: value.ipAddress,
        unitInfo: value.unitInfo,
        simCardNumber: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.simCardNumber)),
        anyDeskAddress: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.anyDeskAddress))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stock: null;
} | {
    reliable: null;
} | {
    wattmaster: null;
} | {
    niagara: null;
}): ControlsType {
    return "stock" in value ? ControlsType.stock : "reliable" in value ? ControlsType.reliable : "wattmaster" in value ? ControlsType.wattmaster : "niagara" in value ? ControlsType.niagara : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ibr600C150M: null;
} | {
    ibr700C4D: null;
}): CradlepointModel {
    return "ibr600C150M" in value ? CradlepointModel.ibr600C150M : "ibr700C4D" in value ? CradlepointModel.ibr700C4D : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Device>): Array<Device> {
    return value.map((x)=>from_candid_Device_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ControlsType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlsType): _ControlsType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_CradlepointModel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CradlepointModel): _CradlepointModel {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CradlepointModel | null): [] | [_CradlepointModel] {
    return value === null ? candid_none() : candid_some(to_candid_CradlepointModel_n6(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ControlsType): {
    stock: null;
} | {
    reliable: null;
} | {
    wattmaster: null;
} | {
    niagara: null;
} {
    return value == ControlsType.stock ? {
        stock: null
    } : value == ControlsType.reliable ? {
        reliable: null
    } : value == ControlsType.wattmaster ? {
        wattmaster: null
    } : value == ControlsType.niagara ? {
        niagara: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CradlepointModel): {
    ibr600C150M: null;
} | {
    ibr700C4D: null;
} {
    return value == CradlepointModel.ibr600C150M ? {
        ibr600C150M: null
    } : value == CradlepointModel.ibr700C4D ? {
        ibr700C4D: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
